### ISSUE TITLE
Editor returns  nothing

### ISSUE THREAD

**Issue by notzippy** [suyati/line-control#10]
From the demo.html
var editor = $("#placeHolder").Editor();

editor is undefined

**Comment by thatguyzee** [comment]
The plugin does not return a jQuery object. A little strange when to document says it does.
To use the plugin operations
$('#editor').Editor('setText','<p>Text to set in editor</p>');
I'm sure this will be fixed in the future.

**Comment by thatguyzee** [comment]
The plugin does not return a jQuery object. A little strange when to document says it does.
To use the plugin operations
`$('#editor').Editor('setText','Text to set in editor');`
I'm sure this will be fixed in the future.

**Comment by nmohanan** [comment]
To add the plugin to your project, just include the JS and CSS files to your HTML template:

<script src="editor.js"></script>
<link type="text/css" href="editor.css" rel="stylesheet"/>

and then in your script section just call:
var editor = $("#placeHolder").Editor();

**Comment by Pruus** [comment]
A little late, but could you provide me with a example for using the script by fill use $content as filled content to use? An a example to read the edited content. PLEASE!!!!!
