### ISSUE TITLE
Documentation - How to?

### ISSUE THREAD

**Issue by dottodot** [suyati/line-control#11]
Could do with some documentation on what's possible and how to do it.

For example I'm trying to set the default value of the editor to what is returned from my database, but not sure how to do this.

**Comment by alexramdesigner** [comment]
Can you give us a more detailed example, please.

**Comment by rgaba** [comment]
I wouldn't mind some additional documentation as well.  I'm pulling the html from a mySql database and then using the built-in setText function to populate the text area.  However, if the html in the database has a single or double quote, the function completely blows up.   I'm now using php's htmlentities to convert the special characters to html, but now the text area is getting populated with html.

**Comment by nmohanan** [comment]
$("#placeHolder").Editor("setText", "Hello")

**Comment by rgaba** [comment]
Thank you very much, this is a GREAT plugin!  I also found what I was missing to get this to work in PHP, I had to do an addslashes to the html I was storing in the database. This way, any single or double quotes I had in my html would not break in the JavaScript.
