### ISSUE TITLE
Disable past content with format

### ISSUE THREAD

**Issue by diogomaximo** [suyati/line-control#14]
Hi, do you know how can i disable paste a content with font-color/font-size on rich text?
Can i enable only raw text with a default format.
Is it possible do it using this current version of component?

**Comment by nmohanan** [comment]
It's not an issue with the plugin, Thank you for your valuable suggestion, we will consider this feature, line-control is an open source project, everyone can contribute to this community. once again Thank you for your valuable suggestion
