### ISSUE TITLE
How to get value?

### ISSUE THREAD

**Issue by daviseford** [suyati/line-control#20]
Hi. I have this textarea set up: var editor = $("#test").Editor();

How do I find the value of $("#test")? I have seen references to getText(), but I don't know how to use it. I want to copy the text from this textarea to another.

Thanks.

**Comment by nmohanan** [comment]
Using below script you can get the value from  the editor.
 <script type="text/javascript">
		$(document).submit( function() {
            
         $("#txtEditor").val($('.Editor-editor').html());                    
         
    });
  </script>
