### ISSUE TITLE
textarea instead of div

### ISSUE THREAD

**Issue by sakirayan78** [suyati/line-control#23]
Is it possibale using or generating instead of this piece of code
div style="overflow: auto;" class="Editor-editor" contenteditable="true">some values</div

this one textarea  class="Editor-editor"> some values</textarea

in that way I guess it is more useable ,when we posting data to server.

**Comment by xOneca** [comment]
The problem is `textarea`s can't do rich text formatting. That's why a `div` is used.

**Comment by sakirayan78** [comment]
Is it possible assign the edit.html() values in editor.js  to <textarea>.In that way I can post the server textarea values.

**Comment by xOneca** [comment]
Yes. Please, see [README.md](https://github.com/suyati/line-control/blob/master/README.md) for how to get and set text to/from the editor.

**Comment by sakirayan78** [comment]
:) I have already read that.I am trying to write custome helper for asp.net mvc ,so that those get and set method not work on the server side .thats why I asked it.If changes happened to div tags ,reflect to the textarea which is generated automatically,would be nice

**Comment by xOneca** [comment]
You have to use Javascript for the editor to work, and you must use Javascript to set/get text to the rich text editor.

To load text from the textarea to the rich editor you can use:

```javascript
var $textarea = $("#textarea-id");
$textarea.Editor("setText", $textarea.text());
```

Then, to bring back the new text to the `textarea` you can use:

```javascript
var $textarea = $("#textarea-id");
$textarea.text($textarea.Editor("getText"));
```

This last one can be done in the `onsubmit` event, so before the form is submitted, the `textarea` will be updated.

**Comment by sakirayan78** [comment]
in the end I can generate html codes using this :) @Html.LineEdit(m=>m.Name,"controlerid");

**Comment by xOneca** [comment]
I don't speak ASP, sorry. Did you get to post the textarea content? If you didn't, can you please post the generated relevant HTML code so I can help you better? I can't assist you with ASP, but I can help on the HTML and Javascript code you need to produce with ASP...
