### ISSUE TITLE
How to give restriction for Number of Characters?

### ISSUE THREAD

**Issue by RVP04** [suyati/line-control#25]
Actually in case if i need restriction for number of characters to typed how can i do that. Please provide option for that. Because if i use in mobile app then i need that feature.

**Comment by nmohanan** [comment]
Thank you for your valuable suggestion, we will consider this feature, line-control is an open source project, everyone can contribute to this community. once again Thank you for your valuable suggestion.

**Comment by madsbrydegaard** [comment]
I had this problem and solved it by counting bytes before submit as part of form validation

```
var bytecount = encodeURI($(this).serialize()).split(/%..|./).length - 1;
if (bytecount > 1024) {
   alert("Size exceed 1MB");
}
```
