### ISSUE TITLE
Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by madsbrydegaard** [suyati/line-control#29]
I get the error:
editor.js:1547 Uncaught TypeError: Cannot read property 'html' of undefined

When trying to setText...
$("#content").Editor('setText', $("#content").text());

**Comment by xOneca** [comment]
Why has been `$(this).data("editor")` reference lost? O.o

**Comment by madsbrydegaard** [comment]
Well if I knew I would not have the problem...
Do you have any idea?

**Comment by xOneca** [comment]
Good to know it wasn't a bug... ;)

Yeah, probably the `setText` part should be included with the simplest example of initialization. After all, it's common to initialize the editor with some content...

Cheers

**Comment by sajalsuraj** [comment]
I am still facing this problem. How can I solve this ?
