### ISSUE TITLE
Is there an online live demo?

### ISSUE THREAD

**Issue by dandv** [suyati/line-control#33]

**Comment by nmohanan** [comment]
Yes, Please check the below URL
http://www.jqueryscript.net/demo/Responsive-WYSIWYG-Text-Editor-with-jQuery-Bootstrap-LineControl-Editor/

**Comment by dandv** [comment]
Thank you. Maybe add it as the website for this repo?

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by suyog9189** [comment]
Thanks, but I have one doubt, when I clicked on bold/italic or any other button , that button is not selected , Like in MS word if we click on bold button it will highlighted.(
![123](https://cloud.githubusercontent.com/assets/12697245/16947804/b60f7584-4dce-11e6-82f6-4996c29f0a79.png) 
) how to do with this editor ?

**Comment by nmohanan** [comment]
You can do some custom coding.
