### ISSUE TITLE
Multiple editors on one page

### ISSUE THREAD

**Issue by Skyxo** [suyati/line-control#40]
How can I use this Editor twice on one page? If I create two textarea's with same class (here .form-control) only one editor is shown. The first textarea is hidden.
Field for textarea:
<textarea name="signature" class="form-control"></textarea>
<textarea name="description" class="form-control"></textarea>

Editor declaration:
$('textarea.form-control').Editor();

How can I solve this problem?

**Comment by xOneca** [comment]
You must call `Editor()` for each textarea individually. `Editor()` will not do it for you.

**Comment by prharish07** [comment]
I had called each Editors individually and  thats showing good all.
Bu the issue now is, if I tried to upload the image for the second editor , its inserting into the first editor only . 
How can I make work each image upload of each editor works itself not all to the first editor 

please reply me as fast as possible
