### ISSUE TITLE
Unable to upload content on MYSQL from editor

### ISSUE THREAD

**Issue by mayank-bothra** [suyati/line-control#41]
Hi 

I am trying to insert the content of the editor into database but its not being done.
Please Help me out with this.

**Comment by TonyFrancis** [comment]
@mayank-bothra can you show the code

**Comment by mayank-bothra** [comment]
<?php 

		include 'connect.php';

		if (isset($_POST['submit'])) {
			
			$text = $_POST['text'];

			$sql = "INSERT INTO domestic(p_overview) VALUES ('$text')";
			$result = mysql_query($sql);
			if ($result) {
				echo "Done";
			}else{
				echo mysql_error();
			}
		}


		?>

		<!DOCTYPE html>
		<html lang="en">
		<head>
			<meta charset="UTF-8">
			<title>Document</title>
		    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" />
		                <link rel="stylesheet" href="img/font-awesome/css/font-awesome.min.css" />
		                 <link rel="stylesheet" href="css/editor.css" />
		</head>
		<body>
			<form action="" method="POST">
				<textarea name="text" id="txtEditor" cols="30" rows="10"></textarea>
				<input type="submit" name="submit">
			</form>

		<script src="js/jquery.min.js"></script>
		    	<script src="bootstrap/js/bootstrap.min.js"></script>
		    	<script src="js/editor.js"></script>

		    	<script>
		    		$(document).ready(function() {
		            	$("#txtEditor").Editor();
		        	});
		    	</script>	
		</body>
		</html>

**Comment by TonyFrancis** [comment]
Please refer this issue https://github.com/suyati/line-control/issues/7

**Comment by mayank-bothra** [comment]
Thanks @TonyFrancis. Its Done !!
