### ISSUE TITLE
Saving edited content

### ISSUE THREAD

**Issue by 2braincells2go** [suyati/line-control#49]
NOTE: I had attempted to contact via your email address shown here at GitHub but email was returned... Please forgive me for asking question that is not real issue but in need of some assistance, please.

Hi. Firstly, nice job on LineControl! Thank you for sharing on GitHub.

I teach at a very low income school for troubled teens and this means our
budget is null, like in nothing:) So I do not have any type of support
channels except for myself and the internet.

Would like to implement your LineControl into some simple software. It
creates certificates.

Example:

Software displays a form and teachers input desired content. I would like
to use LineControl so teachers can customize the certificates with editor
but cannot figure out how to save the editor content to HTML/PHP file for printing?

Issue I cannot grasp is how to save the LineControl content into a file.
Could you point me to possible solution?

Far form techie so basic help would be much appreciated.

Thank you for your time,

Woody

**Comment by nmohanan** [comment]
Please refer the issue https://github.com/suyati/line-control/issues/7

**Comment by nmohanan** [comment]
Please refer the issue https://github.com/suyati/line-control/issues/41

**Comment by 2braincells2go** [comment]
Thank you @nmohanan! I will review those issues again and see if can grasp what I am doing wrong.
