### ISSUE TITLE
Show/Hide toolbar buttons List of names?

### ISSUE THREAD

**Issue by drdal** [suyati/line-control#63]
I need to hide a lot of buttons- 
Is there a list of names somewhere?

**Comment by nmohanan** [comment]
No, we haven't listed any where. just check the code.

**Comment by chmike02** [comment]
var settings ={
            'fonts': false,
            'font_size':false,
            'styles':true,
    
            'bold': true, 
            'italics': true,
            'underline':true,
            'color':false,

            'l_align':true,
            'r_align':true,
            'c_align':true,
            'justify':false,

            'indent':true,
            'outdent':true,
            'block_quote':false,

            'undo':false,
            'redo':false,

            'insert_link':false,
            'unlink':false,
            'insert_img':false,
            'insert_table':false,
            'hr_line':false,
            'strikeout':false,

            'select_all':false,
            'rm_format':false,
            
    
            'insertImage':false,
            'createTable':false,
           
            'print':false,
            'source':false,
            'togglescreen':false,
            'splchars':false,
        }

**Comment by tkserver** [comment]
Thanks very much.  Did I miss this in the documentation?
