### ISSUE TITLE
How can i set formatted text in editor

### ISSUE THREAD

**Issue by roman-morev** [suyati/line-control#69]
I have formatted text in editor like "6i86iyuityvb  **fghf** gh fghf gh". But when I set this text to editor on startup, editor shows me only text with service symbols not formatted.

**Comment by leopoldwong** [comment]
maybe the text is escaped ,try to use console.log() to see what you get

**Comment by abalakrishnan** [comment]
You just place your test in your text area, Editor will automatically show this
<textarea>--your text here--</textarea>
