### ISSUE TITLE
What's wrong with the editor using PHP

### ISSUE THREAD

**Issue by satrianivzla** [suyati/line-control#7]
Hi there.
I have several hours trying to make it work just using the demo file that you made, and the post variable always is lost - no matter if I put the editor.css and editor.js in the common folders css and js.
Can you please put a simple full example running where I can see what can be wrong?
Cheers

**Comment by alexramdesigner** [comment]
Hi,

How I can get te text in the editor?

**Comment by bossyman** [comment]
in the newer versions there is no id attribute #contentarea so you would have to use the class .Editor-editor instead, and the above example would then work properly.

**Comment by xOneca** [comment]
It is missing, because you can't have same ID repeated in the same document (when more than one editor is present). You should reference the content area by the class `Editor-editor` as you mentioned, or (better) manipulate it with `$("#textarea-id").Editor(...)` methods.

**Comment by xOneca** [comment]
Remember, if the editor is in "show source" mode, `getText` and `setText` functions are aware of it and will grab/set content correctly. But if you access the content directly, you could break the editor.

**Comment by mathiazhagan01** [comment]
Hi, I have read the above solutions, And I have tried this, and txtEditor returns nothing. What should I do in this case?

<form id="submitForm">
 <textarea id="txtEditor" name="txtEditor"></textarea>
                    <button type="submit" class="btn btn-success">Send</button>
                </form>

$('#submitForm').submit(function (e) {
    e.preventDefault();
            console.log($('#submitForm').serialize());
    $.ajax({
        type: 'POST',
        url: 'submit.php',
        data: $('#submitForm').serialize(),
        success: function (response) {
            console.log(response);
        }
    });
});

**Comment by xOneca** [comment]
The editor doesn't update the textarea by itself. You have to use `getText` as described in [README.md](https://github.com/suyati/line-control/blob/master/README.md#get-text-from-editor) to update it before serializing the form.

**Comment by kg1thub** [comment]
Hello Team, 
Greetings!!! 

I am trying to get the no of characters (i.e. excluding the html tags and exact what it shows in the status bar "Charaters : 0" .... but I am unable to get it. 

Can any one explain that how I can get number of characters shown in statusbar using JQuery? 

Thanks, 
Kamleshkumar Gujarathi

**Comment by kg1thub** [comment]
I know one thing that we have to create object
`var editor =  $("#inputcontrolID").data('editor');`
But when I am not getting var count = methods.getCharCount.apply(editor);
Am I missing anything ? 

Thanks 
Kamleshkumar Gujarathi

**Comment by sandeep122** [comment]
**Worked for me.**
```
<script>
$(document).ready(function() 
{
  $("#txtEditor").Editor();
});
			
$(function()
{
  $('#save').click(function () 
  {
   //get text in div and assign to textarea
   var str = $( '#editor2 .Editor-editor' ).text();
   $('#txtEditor').val(str);
  });
});
</script>
```

// #editor2 is div id
// #save is submit id

**Comment by adwaithss** [comment]
<script>
        $(document).ready(function() {
            $("#txtEditor").Editor();
        });
    </script>
    <script>
        $(document).submit(function() {
            $("#txtEditor").val($(".Editor-editor").html());
        });
    </script>

this worked for me
