### ISSUE TITLE
Bold Italic Underline

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [suyati/line-control#8]
Hi,

I am using LineControl Editor. There is option to make text style as bold, italic and underline. It works fine. But I want to add functionality of auto focusing. It means when bold text is selected, then "B" should get highlighted. If text which has style as underline and italic is selected or clicked , then both "U" and "I" should get selected. How do I do it ? 
Please help me.

**Comment by matinca** [comment]
It's as simple as adding and setting the data-toggle="button" attribute in createMenuItem function when creating a basic item (that is no modal or dropdown etc.). So line 1421 should look like this:
var menuWrapElement = $("<a/>",{href:'javascript:void(0)', class:'btn btn-default', "data-toggle":"button"});

With it bootstrap appropriately toggles the active class on the element.
