### ISSUE TITLE
when a page need to use two or more of the Editor problems

### ISSUE THREAD

**Issue by dralonliang** [suyati/line-control#83]
hi suyati, We using your LineControl Editor,  but found a problem in the process of using. when a page need to use two or more of the Editor, the Editor menu tools will be positioning confusion. For example，We insert a table or image from menu on other Editor, the image and table still into the first Editor, but others none. hope to get your help and solve, thank you very much!

**Comment by dralonliang** [comment]
Are you still maintaining this project？

**Comment by nmohanan** [comment]
Yes

**Comment by dralonliang** [comment]
The problem hasn't been solved yet

**Comment by nmohanan** [comment]
https://github.com/suyati/line-control/pull/96


Can you check with this.

**Comment by dralonliang** [comment]
thank you very much!
